// DAX Query
DEFINE
	VAR __DS0FilterTable = 
		FILTER(
			KEEPFILTERS(VALUES('workorder'[Estado])),
			NOT('workorder'[Estado] IN {"CAN"})
		)

	VAR __DS0FilterTable2 = 
		TREATAS({0,
			BLANK()}, 'workorder'[Es Tarea])

	VAR __DS0FilterTable3 = 
		FILTER(
			KEEPFILTERS(VALUES('matusetrans'[Fecha Transacción])),
			AND(
				'matusetrans'[Fecha Transacción] >= DATE(2018, 8, 1),
				'matusetrans'[Fecha Transacción] < DATE(2019, 1, 1)
			)
		)

	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			ROLLUPADDISSUBTOTAL(
				'workorder'[Organización], "IsGrandTotalRowTotal",
				'site'[Descripción], "IsDM0Total",
				'matusetrans'[Cuenta Débito del LM], "IsDM2Total"
			),
			__DS0FilterTable,
			__DS0FilterTable2,
			__DS0FilterTable3,
			"Linecost_Total", 'Metricas'[Linecost_Total],
			"Actlabcosto_Total", 'Metricas'[Actlabcosto_Total],
			"AggCostoTotal", 'Metricas'[AggCostoTotal]
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(
			501,
			__DS0Core,
			[IsGrandTotalRowTotal],
			1,
			'workorder'[Organización],
			1,
			[IsDM0Total],
			1,
			'site'[Descripción],
			1,
			[IsDM2Total],
			1,
			'matusetrans'[Cuenta Débito del LM],
			1
		)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	[IsGrandTotalRowTotal],
	'workorder'[Organización],
	[IsDM0Total],
	'site'[Descripción],
	[IsDM2Total],
	'matusetrans'[Cuenta Débito del LM]
