name: Power BI Release Notification Workflow Caller 

on:
  pull_request_target:
    types:
      - closed

jobs:
  call-reusable:
    uses: Chakua51/.github/.github/workflows/reusable-workflows_powerbi-release-notification.yml@main
    secrets: inherit
    with:
      email_recipients: 'chacui1951@comunidad.unam.mx'

