name: Power BI Componentes Workflow Caller

on:
  workflow_dispatch:
    inputs:
      componente:
        description: 'Selecciona el componente'
        required: true
        type: choice
        options:
          - Reporte1
          - Reporte2

jobs:
  set-folder-mapping:
    runs-on: ubuntu-latest
    outputs:
      mapping: ${{ steps.set-mapping.outputs.mapping }}
    steps:
      - id: set-mapping
        run: |
          echo "mapping<<EOF" >> $GITHUB_OUTPUT
          echo '{
            "Reporte1": "(RP-CID-TBL) Tablero Ejemplos.Report",
            "Reporte2": [
              "(RP-CA-TECSERVICES.02) Backlog_Otras_Areas.Report",
              "(SM-CA-TECSERVICES.02) Backlog_Otras_Areas.SemanticModel"
            ]
          }' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  call-develop-to-main:
    needs: set-folder-mapping
    uses: Chakua51/.github/.github/workflows/reusable-workflows_powerbi-componentes-develop-hacia-main.yml@main
    secrets: inherit
    with:
      componente: ${{ github.event.inputs.componente }}
      folder_mapping: ${{ needs.set-folder-mapping.outputs.mapping }}
      modelDBID: ${{ vars.POWERBI_PROD_SM_ID }}
      reviewer: "IsaacLeyva-01"
